version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    container_name: apache1
    ports:
      - "80:80"
    volumes:
      - ./docker/apache/api.conf:/etc/apache2/sites-available/000-default.conf
      - .:/var/www/html
      - ./docker/apache/php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    restart: always
    networks:
      - incancer

networks:
  incancer:
    driver: bridge
